version: '3.8'
services:
  postgres_db_bookmark:
    container_name: postgres_db_bookmark
    image: postgres:14-alpine3.18
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db_bookmark
    ports:
      - "5432:5432"
    volumes:
      - volume_postgres_db_bookmark:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready -U postgres | grep 'accepting connections' || exit 1"
      interval: 2s
      timeout: 20s
      retries: 10
    networks:
      - db_net

  bookmark-service:
    container_name: bookmark-service
    image: pblgllgs/bookmark-service:latest
    pull_policy: always
    environment:
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "18080:8080"
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health | grep UP || exit 1"
      start_period: 10s
      interval: 5s
      timeout: 3s
      retries: 5
    depends_on:
      postgres_db_bookmark:
        condition: service_healthy
    networks:
      - spring-net
      - db_net

  bookmark-frontend-service:
    container_name: bookmark-frontend-service
    image: pblgllgs/bookmark-frontend-service:latest
    pull_policy: always
    environment:
      SERVER_SIDE_API_BASE_URL: http://bookmark-service:8080
      CLIENT_SIDE_API_BASE_URL: http://localhost:18080
    ports:
      - "3000:3000"
    depends_on:
      bookmark-service:
        condition: service_healthy
    networks:
      - spring-net

volumes:
  volume_postgres_db_bookmark:
    external: false
networks:
  spring-net:
  db_net: