INSERT INTO bookmarks (title, url, created_at) VALUES ('Spring Framework', 'https://spring.io/', CURRENT_TIMESTAMP);
INSERT INTO bookmarks (title, url, created_at) VALUES ('React Documentation', 'https://reactjs.org/', CURRENT_TIMESTAMP);
INSERT INTO bookmarks (title, url, created_at) VALUES ('Java Documentation', 'https://docs.oracle.com/en/java/', CURRENT_TIMESTAMP);
INSERT INTO bookmarks (title, url, created_at) VALUES ('Docker Hub', 'https://hub.docker.com/', CURRENT_TIMESTAMP);
INSERT INTO bookmarks (title, url, created_at) VALUES ('Kubernetes Documentation', 'https://kubernetes.io/docs/', CURRENT_TIMESTAMP);
INSERT INTO bookmarks (title, url, created_at) VALUES ('Jenkins Official Website', 'https://www.jenkins.io/', CURRENT_TIMESTAMP);
INSERT INTO bookmarks (title, url, created_at) VALUES ('Git Documentation', 'https://git-scm.com/doc', CURRENT_TIMESTAMP);
INSERT INTO bookmarks (title, url, created_at) VALUES ('Node.js Documentation', 'https://nodejs.org/en/docs/', CURRENT_TIMESTAMP);
INSERT INTO bookmarks (title, url, created_at) VALUES ('PostgreSQL Documentation', 'https://www.postgresql.org/docs/', CURRENT_TIMESTAMP);
INSERT INTO bookmarks (title, url, created_at) VALUES ('AWS Documentation', 'https://docs.aws.amazon.com/', CURRENT_TIMESTAMP);
INSERT INTO bookmarks (title, url, created_at) VALUES ('Angular Documentation', 'https://angular.io/docs', CURRENT_TIMESTAMP);
INSERT INTO bookmarks (title, url, created_at) VALUES ('Python Official Documentation', 'https://docs.python.org/3/', CURRENT_TIMESTAMP);
INSERT INTO bookmarks (title, url, created_at) VALUES ('Azure Documentation', 'https://docs.microsoft.com/en-us/azure/', CURRENT_TIMESTAMP);
INSERT INTO bookmarks (title, url, created_at) VALUES ('Vue.js Documentation', 'https://vuejs.org/', CURRENT_TIMESTAMP);
INSERT INTO bookmarks (title, url, created_at) VALUES ('Elasticsearch Documentation', 'https://www.elastic.co/guide/en/elasticsearch/reference/current/index.html', CURRENT_TIMESTAMP);
INSERT INTO bookmarks (title, url, created_at) VALUES ('Flutter Documentation', 'https://flutter.dev/docs', CURRENT_TIMESTAMP);
INSERT INTO bookmarks (title, url, created_at) VALUES ('GraphQL Documentation', 'https://graphql.org/learn/', CURRENT_TIMESTAMP);
INSERT INTO bookmarks (title, url, created_at) VALUES ('Rust Documentation', 'https://www.rust-lang.org/learn', CURRENT_TIMESTAMP);
INSERT INTO bookmarks (title, url, created_at) VALUES ('Terraform Documentation', 'https://www.terraform.io/docs/', CURRENT_TIMESTAMP);
INSERT INTO bookmarks (title, url, created_at) VALUES ('Express.js Documentation', 'https://expressjs.com/', CURRENT_TIMESTAMP);
INSERT INTO bookmarks (title, url, created_at) VALUES ('Ansible Documentation', 'https://docs.ansible.com/', CURRENT_TIMESTAMP);
INSERT INTO bookmarks (title, url, created_at) VALUES ('Swift Documentation', 'https://docs.swift.org/swift-book/', CURRENT_TIMESTAMP);
INSERT INTO bookmarks (title, url, created_at) VALUES ('Ruby on Rails Guides', 'https://guides.rubyonrails.org/', CURRENT_TIMESTAMP);
INSERT INTO bookmarks (title, url, created_at) VALUES ('TensorFlow Documentation', 'https://www.tensorflow.org/guide', CURRENT_TIMESTAMP);
INSERT INTO bookmarks (title, url, created_at) VALUES ('Go Documentation', 'https://golang.org/doc/', CURRENT_TIMESTAMP);
INSERT INTO bookmarks (title, url, created_at) VALUES ('MongoDB Documentation', 'https://docs.mongodb.com/', CURRENT_TIMESTAMP);
INSERT INTO bookmarks (title, url, created_at) VALUES ('Apache Kafka Documentation', 'https://kafka.apache.org/documentation/', CURRENT_TIMESTAMP);
INSERT INTO bookmarks (title, url, created_at) VALUES ('Redux Documentation', 'https://redux.js.org/', CURRENT_TIMESTAMP);
INSERT INTO bookmarks (title, url, created_at) VALUES ('Chef Documentation', 'https://docs.chef.io/', CURRENT_TIMESTAMP);
INSERT INTO bookmarks (title, url, created_at) VALUES ('Scrum Guide', 'https://www.scrumguides.org/scrum-guide.html', CURRENT_TIMESTAMP);
