spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  flyway:
    locations: classpath:/db/migration/{vendor}
  datasource:
    url: jdbc:postgresql://postgres_db_bookmark:5432/db_bookmark
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
