apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-configmap
data:
  server-side-api-base-url: "http://bookmark-backend-service:8080"
  client-side-api-base-url: "http://k8s-cluster.com:18080"
  
