apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookmark-frontend-service
  labels:
    app: bookmark-frontend-service
    version: latest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookmark-frontend-service
  template:
    metadata:
      labels:
        app: bookmark-frontend-service
    spec:
      initContainers:
        - name: helper
          image: busybox:1.31
          command:
            - "/bin/sh"
            - "-c"
            - |
              until nc -zv bookmark-backend-service 8080
              do
                echo "Esperando a que el servicio de backend esté disponible..."
                sleep 2
              done
      containers:
      - image: pblgllgs/bookmark-frontend-service:latest
        name: bookmark-frontend-service
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
          - name: SERVER_SIDE_API_BASE_URL
            valueFrom:
              configMapKeyRef:
                name: frontend-configmap
                key: server-side-api-base-url
          - name: CLIENT_SIDE_API_BASE_URL
            valueFrom:
              configMapKeyRef:
                name: frontend-configmap
                key: client-side-api-base-url
        resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: bookmark-frontend-service
spec:
  type: NodePort
  selector:
    app: bookmark-frontend-service
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
    nodePort: 30080
