version: '3.8'
services:
  postgres_db_bookmark:
    container_name: postgres_db_bookmark
    image: postgres:14.3
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db_bookmark
    ports:
      - "5432:5432"
    volumes:
      - volume_postgres_db_bookmark:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready -U postgres | grep 'accepting connections' || exit 1"
      interval: 2s
      timeout: 20s
      retries: 10
    networks:
      - spring-net

  bookmark-service:
    container_name: bookmark-service
    image: pblgllgs/bookmark-service:1.0.0
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_db_bookmark:5432/db_bookmark
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
    depends_on:
      postgres_db_bookmark:
        condition: service_healthy
    networks:
      - spring-net
volumes:
  volume_postgres_db_bookmark:
    external: false
networks:
  spring-net: