name: Build and push image

on:
  push:
    branches:
      - '**'
env:
  VERSION: latest
  REPOSITORY: pblgllgs
  BACKEND: bookmark-service
  FRONTEND: bookmark-frontend-service

jobs:
  build-bookmark-service:
    name: Build bookmark service
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./bookmark-service

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: install jdk 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'

      - name: build with maven
        run: ./mvnw verify

      - if: ${{ github.ref == 'refs/heads/master' }}
        name: Build and push
        run: |
          docker build -t $REPOSITORY/$BACKEND:$VERSION .
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push $REPOSITORY/$BACKEND:$VERSION

  build-bookmark-frontend-service:
    name: Build bookmark frontend service
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./bookmark-frontend-service

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: install nodejs 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
          cache-dependency-path: bookmark-frontend-service/yarn.lock
      - name: Install dependencies
        run: yarn

      - name: build
        run: yarn build

      - if: ${{ github.ref == 'refs/heads/master' }}
        name: Build and push
        run: |
          docker build -t $REPOSITORY/$FRONTEND:$VERSION .
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push $REPOSITORY/$FRONTEND:$VERSION