name: Build and push image

on:
  push:
    branches:
      - '**'
env:
  VERSION: 2.0.0

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./bookmark-service

    steps:
      - uses: actions/checkout@v3

      - name: install jdk 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'

      - name: build with maven
        run: ./mvnw verify

      - if: ${{ github.ref == 'refs/heads/master' }}
        name: Build and push
        run: |
          docker build -t pblgllgs/bookmark-service:latest .
          docker tag pblgllgs/bookmark-service:latest pblgllgs/bookmark-service:$VERSION
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push ${{ secrets.DOCKER_USERNAME }}/bookmark-service:$VERSION
          docker push ${{ secrets.DOCKER_USERNAME }}/bookmark-service:latest
